spring:
  application:
    name: langchain
  datasource:
    url: jdbc:mysql://172.25.74.102:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: remote_root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 172.25.74.102:8848
      config:
        import-check:
          enabled: false

server:
  port: 10000
mybatis:
  mapper-locations: classpath:mapper/*.xml