spring:
  application:
    name: langchain
  datasource:
#    url: jdbc:mysql://172.25.74.102:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: remote_root
    url: jdbc:mysql://172.31.187.223:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true


mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.example.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

server:
  port: 10000